# Name of various directories
FRONTEND_DIR = "frontend"
SRC_DIR = "src"
REDUX_DIR = "redux"
ACTIONS_DIR = "actions"
REDUCERS_DIR = "reducer"
MIDDLEWARE_DIR = "middleware"
COMPONENTS_DIR = "components" 
ENVIRONMENTS_DIR = "environments"
HELPERS_DIR = "helpers"
INTERFACES_DIR = "interfaces"
UTILS_DIR = "utils"
HOOKS_DIR = "hooks"
PAGES_DIR = "pages"
WEBPACK_DIR = "webpack"
STATIC_DIR = "static"
TEMPLATES_DIR = "templates"

#File Names
INDEX_TS_FILE = "index.ts"
INDEX_TSX_FILE = "index.tsx"
STORE_TS_FILE = "store.ts"
APP_TSX_FILE = "App.tsx"
HOME_TSX_FILE = "home.tsx"
PACKAGE_JSON_FILE = "package.json"
TS_CONFIG_FILE = "tsconfig.json"
WEBPACK_DEV_CONFIG_FILE = "webpack.dev.js"
WEBPACK_PROD_CONFIG_FILE = "webpack.prod.js"
WEBPACK_COMMON_CONFIG_FILE = "webpack.common.js"
HOME_HTML_FILE = "home.html"
INDEX_HTML_FILE = "index.html"
